In [1]:
from clean_name import clean_name, add_issue

In [2]:
## define variable
# for 1st function
exel_file = "wl_zqcredit_04.2025.xlsx" 
name_column = "ชื่อ-สกุล"

# for 2nd function
issuenote_column = "ผลการตรวจสอบ" # column that assign issue
note_txt = "ตรวจสอบคำนำหน้า" # output text
target_column = "คำนำหน้า" # column name that need to check
target_value = {'ร.ต.อ', 'ส.ต.อ'} # prefix that need to issue note on

In [3]:
df_clean = clean_name(exel_file, name_column)

In [4]:
df_clean.head(10)

                     ชื่อ-สกุล คำนำหน้า         ชื่อ    นามสกุล
0        น.ส.ทัศนีย์ โปรานันท์     น.ส.      ทัศนีย์  โปรานันท์
1              นายคนอง  รักเสน      นาย         คนอง     รักเสน
2         นางสาวจริยาวดี สัพโส   นางสาว     จริยาวดี      สัพโส
3            นางคำกอง ต๊อดแก้ว      นาง        คำกอง   ต๊อดแก้ว
4  นางสาวพัชรินทร์   สายจันทร์   นางสาว    พัชรินทร์  สายจันทร์
5          นายอนันชัย อภิธะนัง      นาย      อนันชัย   อภิธะนัง
6            นางบุญชุม กองแก้ว      นาง       บุญชุม    กองแก้ว
7              นางบุผา กองแก้ว      นาง         บุผา    กองแก้ว
8       นายชัยนารินทร์ วีระแสง      นาย  ชัยนารินทร์    วีระแสง
9          นายสมศักดิ์ วีระแสง      นาย     สมศักดิ์    วีระแสง

In [5]:
df = df_clean # df name that is a result of "clean_name" function

In [6]:
df_clean = add_issue(df, target_column, issuenote_column, target_value, note_txt)

In [24]:
df_clean.isnull().sum()

ชื่อ-สกุล           0
คำนำหน้า           27
ชื่อ                0
นามสกุล            14
ผลการตรวจสอบ    30112
dtype: int64

In [22]:
df_clean[df_clean[issuenote_column].notnull()]

                   ชื่อ-สกุล คำนำหน้า     ชื่อ    นามสกุล     ผลการตรวจสอบ
13317    ร.ต.อำนาจ แก่นเมือง    ร.ต.อ     ำนาจ  แก่นเมือง  ตรวจสอบคำนำหน้า
13653      ส.ต.อธิคม  ศิริตา    ส.ต.อ     ธิคม     ศิริตา  ตรวจสอบคำนำหน้า
13882   ส.ต.อนุรักษ์ แสงแก้ว    ส.ต.อ  นุรักษ์    แสงแก้ว  ตรวจสอบคำนำหน้า
19636  ส.ต.อ พิเชษฐ์ การเร็ว    ส.ต.อ  พิเชษฐ์    การเร็ว  ตรวจสอบคำนำหน้า
21474  ร.ต.อ ประหยัด กองมะลิ    ร.ต.อ  ประหยัด    กองมะลิ  ตรวจสอบคำนำหน้า

In [9]:
df_clean.head(10)

                     ชื่อ-สกุล คำนำหน้า         ชื่อ    นามสกุล ผลการตรวจสอบ
0        น.ส.ทัศนีย์ โปรานันท์     น.ส.      ทัศนีย์  โปรานันท์         None
1              นายคนอง  รักเสน      นาย         คนอง     รักเสน         None
2         นางสาวจริยาวดี สัพโส   นางสาว     จริยาวดี      สัพโส         None
3            นางคำกอง ต๊อดแก้ว      นาง        คำกอง   ต๊อดแก้ว         None
4  นางสาวพัชรินทร์   สายจันทร์   นางสาว    พัชรินทร์  สายจันทร์         None
5          นายอนันชัย อภิธะนัง      นาย      อนันชัย   อภิธะนัง         None
6            นางบุญชุม กองแก้ว      นาง       บุญชุม    กองแก้ว         None
7              นางบุผา กองแก้ว      นาง         บุผา    กองแก้ว         None
8       นายชัยนารินทร์ วีระแสง      นาย  ชัยนารินทร์    วีระแสง         None
9          นายสมศักดิ์ วีระแสง      นาย     สมศักดิ์    วีระแสง         None